apiVersion: v1
kind: Pod
metadata:
  name: annotations-pod
  lables: 
    course: devops
    trainer: siva
  annotations:
    kubernetes.io/created-by: 'udaydara'
    jenkins.build.url: 'https://jenkins.prajai.online/expense/job/backend/54'
spec:
  containers: 
    - name: nginx-container
      image: nginx:latest 


## lables:
##### For filtering, selecting, grouping used for Services, Deployments, CLI filtering

## lables: annotations
##### For extra metadata not used by K8s itself used for CI/CD info, monitoring tools, documentation, tracking

## kubectl get pods -l course=devops

## kubectl describe pod annotations

##Show Only Annotations
## kubectl get pod annotations -o jsonpath="{.metadata.annotations}

