apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ## soft limits
      resources:
        ## soft limits
        requests:
          cpu: "100m"
          memory: "128Mi"
        # limits should be atleast or more than requests i.e hard limit
        limits:
          cpu: "100m"
          memory: "128Mi"


# commands: 
# kubectl describe pod resources

## Requests:    Minimum resources guaranteed for the container
## Limits:      Maximum resources the container can use
