apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
  course: "DevOps with AWS"
  trainer: "uday kumar dara"
  github: "https://github.com/udaydevops-lab/expense-k8s-resources.git"
