apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: secret-container
      image: nginx:latest
      ports:
        - containerPort: 80
      env:
        - name: SECRET_USER
          valueFrom:
            secretKeyRef:
              name: secrets ## (refer the secrets.yaml)
              key: username  ## ( refer the key and value)
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: password
          

## values must be base64 encoded


## Commands:

# kubectl apply -f my-secret.yaml
# kubectl apply -f secret-pod.yaml

# kubectl exec -it secret-pod -- printenv SECRET_USER
# kubectl exec -it secret-pod -- printenv SECRET_PASS