## this is a pod defination
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-app
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-app      # Target the pods with the label 
  ports:
    - protocol: TCP
      port: 80          # service exposed port
      targetPort: 80    # Pod containerPort
  type: ClusterIP       # default type